"""Added columns to table

Revision ID: 30b6354708de
Revises: d936ef365923
Create Date: 2023-07-12 12:55:18.208249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30b6354708de'
down_revision = 'd936ef365923'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(), nullable=True))
    op.drop_constraint('users_telegram_id_key', 'users', type_='unique')
    op.create_unique_constraint(None, 'users', ['email'])
    op.drop_column('users', 'telegram_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('telegram_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='unique')
    op.create_unique_constraint('users_telegram_id_key', 'users', ['telegram_id'])
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
