"""Edit table columns

Revision ID: 656dfde61126
Revises: 70c371909055
Create Date: 2023-07-17 09:06:36.316845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '656dfde61126'
down_revision = '70c371909055'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
