"""Edit table columns

Revision ID: 6ba987ba199d
Revises: c39da3d7665a
Create Date: 2023-07-15 14:05:17.498968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ba987ba199d'
down_revision = 'c39da3d7665a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requests', 'usertg_phone')
    op.drop_column('requests', 'usertg_id')
    op.add_column('users', sa.Column('telegram_id', sa.BIGINT(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'telegram_id')
    op.add_column('requests', sa.Column('usertg_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('requests', sa.Column('usertg_phone', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
