"""Edit table columns

Revision ID: a9c76650aa50
Revises: 6ba987ba199d
Create Date: 2023-07-15 14:05:28.231477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9c76650aa50'
down_revision = '6ba987ba199d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
