"""Added columns to table

Revision ID: c39da3d7665a
Revises: da02208f55b0
Create Date: 2023-07-12 15:41:19.401849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c39da3d7665a'
down_revision = 'da02208f55b0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('urgent', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requests', 'urgent')
    # ### end Alembic commands ###
