"""Added columns to table

Revision ID: da02208f55b0
Revises: 30b6354708de
Create Date: 2023-07-12 15:23:57.316050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da02208f55b0'
down_revision = '30b6354708de'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
