from app.models.parentpage import ParentPage
from app.models.pages import Pages
from app.models.groups import Groups
from app.models.roles import Roles
from app.models.users_model import Users
from app.models.parentfillials import ParentFillials
from app.models.fillials import Fillials
from app.models.suppliers import Suppliers
from app.models.category import Category
from app.models.products import Products
from app.models.brigada import Brigada
from app.models.expanditure import Expanditure
from app.models.telegrams import Telegrams
from app.models.requests import Requests
from app.models.communication import Communication
from app.models.orderproducts import OrderProducts
from app.models.comments import Comments
from app.models.toolparents import ToolParents
from app.models.tools import Tools
from app.models.working import Working
from app.models.cars import Cars
from app.models.toolsorder import ToolsOrder
from app.models.neededtools import NeededTools
from app.models.hrusers import HrUser
from app.models.hrrequest import HrRequest
from app.models.hrquestions import HrQuestions
from app.models.arcexpensetype import ArcExpenseType
from app.models.arcexpense import ArcExpense
from app.models.calendars import Calendars
from app.models.kru_categories import KruCategories
from app.models.kru_tasks import KruTasks
from app.models.kru_finished_tasks import KruFinishedTasks
from app.models.files import Files

